CREATE TABLE TASKS_BOARD (
    ENTITY_ID IDENTITY PRIMARY KEY,
    NAME      VARCHAR(64) NOT NULL
);

CREATE TABLE TASK_STATUS (
    ENTITY_ID IDENTITY PRIMARY KEY,
    NAME      VARCHAR(64) NOT NULL
);

INSERT INTO TASK_STATUS(name)
VALUES ('TO DO'),
       ('IN PROGRESS'),
       ('DONE');

CREATE TABLE IF NOT EXISTS TASK (
    ENTITY_ID          IDENTITY PRIMARY KEY,
    NAME               VARCHAR(128) NOT NULL,
    CREATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    BOARD_ID           BIGINT NOT NULL REFERENCES TASKS_BOARD(ENTITY_ID) ON DELETE CASCADE,
    STATUS_ID          BIGINT NOT NULL DEFAULT 1 REFERENCES TASK_STATUS(ENTITY_ID)
);
