CREATE TABLE IF NOT EXISTS TASK (
    ENTITY_ID          IDENTITY PRIMARY KEY,
    NAME               VARCHAR(256) NOT NULL,
    CREATED_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
