springdoc:
  swagger-ui:
    enabled: true
    path: /docs

persistence:
  dialect: POSTGRES
  url: jdbc:postgresql://task-db:5432/task
  schema: task
  username: task_appl
  password: qwe123
  maxPoolSize: 10
  retry-policy:
    entities:
      task:
        save:
          attempts: 3
          exception: rgo.tt.common.exceptions.UniqueViolationException