CREATE SEQUENCE task_sequence;

CREATE TABLE TASK (
    ENTITY_ID          BIGINT PRIMARY KEY DEFAULT nextval('task_sequence'),
    NAME               VARCHAR(128) NOT NULL,
    CREATED_DATE       TIMESTAMP DEFAULT (now() AT TIME ZONE 'UTC'),
    LAST_MODIFIED_DATE TIMESTAMP DEFAULT (now() AT TIME ZONE 'UTC'),
    BOARD_ID           BIGINT REFERENCES TASKS_BOARD(ENTITY_ID) ON DELETE CASCADE NOT NULL,
    STATUS_ID          BIGINT REFERENCES TASK_STATUS(ENTITY_ID) NOT NULL DEFAULT 1
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TASK TO ${appRole};
GRANT SELECT ON TASK TO ${readerRole};