CREATE SEQUENCE tasks_board_sequence;

CREATE TABLE TASKS_BOARD (
    ENTITY_ID BIGINT PRIMARY KEY DEFAULT nextval('tasks_board_sequence'),
    NAME      VARCHAR(64) NOT NULL
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TASKS_BOARD TO ${appRole};
GRANT SELECT ON TASKS_BOARD TO ${readerRole};