spring:
  main:
    web-application-type: none
    banner-mode: off

armeria:
  ports:
    - port: 8080
      protocols:
        - HTTP

logging:
  config: classpath:logback-local.xml

persistence:
  dialect: H2