springdoc:
  swagger-ui:
    enabled: true
    path: /docs

logging:
  config: classpath:logback-local.xml

persistence:
  dialect: POSTGRES
  url: jdbc:postgresql://localhost:5433/task
  schema: task
  username: task_appl
  password: qwe123
  maxPoolSize: 10
  retry-policy:
    entities:
      task:
        save:
          attempts: 3
          exception: rgo.tt.common.exceptions.UniqueViolationException