spring:
  main:
    web-application-type: none
    banner-mode: off

armeria:
  ports:
    - port: 8080

logging:
  config: classpath:logback-local.xml

app:
  cors:
    origins: 'http://localhost:5173'
    methods: GET, POST, PUT, DELETE
    maxAgeSeconds: 3600

  persistence:
    dialect: H2

  rate-limiter:
    rest-services:
      ValidateRestTaskServiceDecorator:
        - method: findAllForBoard
          limit: 2000
        - method: findByEntityId
          limit: 2000
        - method: findByName
          limit: 2000
        - method: save
          limit: 2000
        - method: update
          limit: 2000
        - method: deleteByEntityId
          limit: 2000
      ValidateRestTasksBoardServiceDecorator:
        - method: findAll
          limit: 2000
        - method: findByEntityId
          limit: 2000
        - method: save
          limit: 2000
        - method: deleteByEntityId
          limit: 2000
      ValidateRestTaskStatusServiceDecorator:
        - method: findAll
          limit: 2000
      ValidateRestTaskTypeServiceDecorator:
        - method: findAll
          limit: 2000