{
 "title": "Armeria Server Overview",
 "description": "Overview your Armeria server using the default metrics provided by Armeria framework using Prometheus.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(armeria_executor_active_threads, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(armeria_http_service_total_duration_seconds_sum[$__rate_interval]))\n/\nsum(rate(armeria_http_service_total_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(rate(armeria_http_service_total_duration_seconds_sum[$__rate_interval] offset 1w))\n/\nsum(rate(armeria_http_service_total_duration_seconds_count[$__rate_interval] offset 1w))",
     "legendFormat": "1 week ago"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(armeria_http_service_response_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(rate(armeria_http_service_response_duration_seconds_count{}[$__rate_interval] offset 1w))",
     "legendFormat": "1 week ago"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(armeria_http_service_requests_total{result=\"failure\"}[$__rate_interval]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Request Error / Success Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(armeria_http_service_requests_total{result=\"failure\"}[$__rate_interval]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(armeria_http_service_requests_total{result=\"success\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(armeria_http_service_timeouts_total[$__rate_interval])) or vector(0)",
     "legendFormat": "Timeouts"
    }
   ]
  },
  {
   "title": "Endpoints Overview",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(armeria_http_service_requests_total{job=~\"$Job\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(armeria_http_service_requests_total{job=\"$Job\", result=\"failure\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(armeria_http_service_timeouts_total{job=~\"$Job\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(armeria_http_service_total_duration_seconds_sum{job=~\"$Job\"}[$__range])) by (service, method)\n/\nsum(increase(armeria_http_service_requests_total{job=~\"$Job\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (service, method) (avg_over_time(armeria_http_service_total_duration_seconds{job=~\"$Job\", quantile=\"0.5\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (service, method) (avg_over_time(armeria_http_service_total_duration_seconds{job=~\"$Job\", quantile=\"0.9\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (service, method) (avg_over_time(armeria_http_service_total_duration_seconds{job=~\"$Job\", quantile=\"0.99\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (service, method) (max_over_time(armeria_http_service_total_duration_seconds{job=~\"$Job\", quantile=\"1.0\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(armeria_http_service_request_length_sum{job=~\"$Job\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(increase(armeria_http_service_response_length_sum{job=~\"$Job\"}[$__range])) by (service, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg(armeria_http_service_total_duration_seconds{job=~\"$Job\"}) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency by Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(armeria_http_service_total_duration_seconds{job=~\"$Job\"}) by (quantile)",
     "legendFormat": "p {{ quantile }}"
    }
   ]
  },
  {
   "title": "Average Duration per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(armeria_http_service_total_duration_seconds_sum{job=~\"$Job\"}[$__rate_interval])) by (service, method)\n/\nsum(rate(armeria_http_service_total_duration_seconds_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
     "legendFormat": "{{ service }}.{{ method }}"
    }
   ]
  },
  {
   "title": "Throughput per Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(armeria_http_service_total_duration_seconds_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
     "legendFormat": "{{ service }}.{{ method }}"
    }
   ]
  },
  {
   "title": "Request Success Count per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"success\"}[$__rate_interval])) by (service, method, result) > 0",
     "legendFormat": "Successful - {{ service }}.{{ method }}"
    }
   ]
  },
  {
   "title": "Request Failure Count per endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"failure\"}[$__rate_interval])) by (service, method, result) > 0",
     "legendFormat": "Failed - {{ service }}.{{ method }}"
    }
   ]
  },
  {
   "title": "Request Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Duration per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(armeria_http_service_request_duration_seconds_sum{job=~\"$Job\"}[$__rate_interval])) by (service, method)\n/\nsum(rate(armeria_http_service_request_duration_seconds_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
       "legendFormat": "{{ service }}.{{ method }}"
      }
     ]
    },
    {
     "title": "Average Request Size per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(armeria_http_service_request_length_sum{job=~\"$Job\"}[$__rate_interval])) by (service, method)\n/\nsum(rate(armeria_http_service_request_length_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
       "legendFormat": "{{ service }}.{{ method }}"
      }
     ]
    },
    {
     "title": "Average Request Duration by Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(armeria_http_service_request_duration_seconds{job=~\"$Job\"}) by (service, method, quantile)",
       "legendFormat": "{{service}}.{{method}} p {{ quantile }}"
      }
     ]
    },
    {
     "title": "Average Request Size by Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(armeria_http_service_request_length{job=~\"$Job\"}) by (service, method, quantile)",
       "legendFormat": "{{service}}.{{method}} p {{ quantile }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Response Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Response Duration per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(armeria_http_service_response_duration_seconds_sum{job=~\"$Job\"}[$__rate_interval])) by (service, method)\n/\nsum(rate(armeria_http_service_response_duration_seconds_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
       "legendFormat": "{{ service }}.{{ method }}"
      }
     ]
    },
    {
     "title": "Average Response Size per Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(armeria_http_service_response_length_sum{job=~\"$Job\"}[$__rate_interval])) by (service, method)\n/\nsum(rate(armeria_http_service_response_length_count{job=~\"$Job\"}[$__rate_interval])) by (service, method)",
       "legendFormat": "{{ service }}.{{ method }}"
      }
     ]
    },
    {
     "title": "Average Response Duration by Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(armeria_http_service_response_duration_seconds{job=~\"$Job\"}) by (service, method, quantile)",
       "legendFormat": "{{service}}.{{method}} p {{ quantile }}"
      }
     ]
    },
    {
     "title": "Average Response Size by Quantiles",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(armeria_http_service_response_length{job=~\"$Job\"}) by (service, method, quantile)",
       "legendFormat": "{{service}}.{{method}} p {{ quantile }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Endpoint Status Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors by HTTP Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (http_status) (increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"failure\"}[$__rate_interval])) > 0",
       "legendFormat": "{{ http_status }} "
      }
     ]
    },
    {
     "title": "Errors by HTTP Status and Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (http_status, service, method) (increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"failure\"}[$__rate_interval])) > 0",
       "legendFormat": "{{service}} - {{ method }} {{ http_status }} "
      }
     ]
    },
    {
     "title": "Success by HTTP Status and Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (http_status) (increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"success\"}[$__rate_interval])) > 0",
       "legendFormat": "{{ http_status }} "
      }
     ]
    },
    {
     "title": "Success by HTTP Status and Endpoint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (http_status, service, method) (increase(armeria_http_service_requests_total{job=~\"$Job\", result=\"success\"}[$__rate_interval])) > 0",
       "legendFormat": "{{service}} - {{ method }} {{ http_status }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor Queued Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_executor_queued_tasks{job=~\"$Job\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executor Completed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(armeria_executor_completed_tasks_total{job=~\"$Job\"}[$__rate_interval])) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executor Remaining Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_executor_queue_remaining_tasks{job=~\"$Job\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Executor Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_executor_active_threads{job=~\"$Job\"}) by (name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Server Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_server_connections{job=~\"$Job\"})",
       "legendFormat": "Active Connection Count"
      }
     ]
    },
    {
     "title": "Server Pending Responses",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_server_pending_responses{job=~\"$Job\"})",
       "legendFormat": "Pending Response Count"
      }
     ]
    },
    {
     "title": "Server Unhandled Exceptions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(armeria_server_exceptions_unhandled_total{job=~\"$Job\"})",
       "legendFormat": "Count"
      }
     ]
    },
    {
     "title": "Server Connection Lifespan",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(armeria_server_connections_lifespan_seconds_sum{job=~\"$Job\"}) / sum(armeria_server_connections_lifespan_seconds_count{job=~\"$Job\"})",
       "legendFormat": "Average Lifespan"
      }
     ]
    }
   ]
  }
 ]
}